class CdnAssetPipelineGrailsPlugin {

    def version = "0.1-SNAPSHOT"
    def grailsVersion = "2.0 > *"
    def dependsOn = ['asset-pipeline': '1.5 > *']
    def loadAfter = ['asset-pipeline','karmanAws']

    def author = "Benoit Hediard"
    def authorEmail = "ben@benorama.Ccm"
    def title = "CDN Asset Pipeline Plugin"
    def description = 'Adds new asset-cdn-push command to upload assets generated by Asset Pipeline Plugin to cloud CDNs.'

    def documentation = "http://github.com/agorapulse/grails-cdn-asset-pipeline"
    def license = "APACHE"
    def organization = [ name: "AgoraPulse", url: "http://www.agorapulse.com/" ]
    def issueManagement = [ system: "github", url: "https://github.com/agorapulse/grails-cdn-asset-pipeline" ]
    def scm = [  url: "https://github.com/agorapulse/grails-cdn-asset-pipeline" ]
    def developers      = [ [name: 'David Estes']  ]
}
