class S3AssetPipelineGrailsPlugin {

    def version = "0.1"
    def grailsVersion = "2.0 > *"
    def dependsOn = ['asset-pipeline': '1.5 > *']
    def loadAfter = ['asset-pipeline']

    def author = "Benoit Hediard"
    def authorEmail = "ben@benorama.Ccm"
    def title = "S3 Asset Pipeline Plugin"
    def description = '''\
Adds new asset-s3-push command to upload assets generated by Asset Pipeline Plugin to Amazon S3.
'''

    def documentation = "http://github.com/agorapulse/grails-s3-asset-pipeline"
    def license = "APACHE"
    def organization = [ name: "AgoraPulse", url: "http://www.agorapulse.com/" ]
    def issueManagement = [ system: "github", url: "https://github.com/agorapulse/grails-s3-asset-pipeline" ]
    def scm = [  url: "https://github.com/agorapulse/grails-s3-asset-pipeline" ]

}
